/**
 * Date and Timezone Constants
 * All timezone and date-related constants for the application
 */

export const TIMEZONES = {
  IST: 'Asia/Kolkata',
  UTC: 'UTC',
  EST: 'America/New_York',
  PST: 'America/Los_Angeles',
  GMT: 'Europe/London',
  DUBAI: 'Asia/Dubai',
  SINGAPORE: 'Asia/Singapore',
  SYDNEY: 'Australia/Sydney',
  TOKYO: 'Asia/Tokyo',
  HONG_KONG: 'Asia/Hong_Kong',
} as const;

export const DEFAULT_TIMEZONE = TIMEZONES.IST;

export const DATE_FORMATS = {
  // Standard formats
  ISO: 'YYYY-MM-DDTHH:mm:ss.SSSZ',
  ISO_DATE: 'YYYY-MM-DD',
  ISO_TIME: 'HH:mm:ss',
  
  // Year and month formats
  YEAR_ONLY: 'YYYY',
  YEAR_MONTH_COMPACT: 'YYYYMM',
  YEAR_MONTH: 'YYYY-MM',
  
  // Simple date formats
  DATE_SLASH_SHORT: 'M/D',
  DATE_SLASH: 'MM/DD',
  DATE_SLASH_YEAR_SHORT: 'M/D/YY',
  DATE_SLASH_YEAR_SHORT_PADDED: 'MM/DD/YY',
  DATE_SLASH_YEAR: 'MM/DD/YYYY',
  
  // Display formats
  DISPLAY_DATE: 'DD MMM YYYY',
  DISPLAY_DATE_SHORT_YEAR: 'DD MMM YY',
  DISPLAY_DATE_FULL: 'DD MMMM YYYY',
  DISPLAY_DATE_SHORT: 'DD/MM/YYYY',
  DISPLAY_DATE_LONG: 'dddd, DD MMMM YYYY',
  DISPLAY_DATE_MEDIUM: 'ddd, MMM DD, YYYY',
  DISPLAY_DATE_WEEKDAY_SHORT: 'dddd, MMM DD',
  DISPLAY_DATE_WEEKDAY_ABBR: 'ddd, MMM DD',
  DISPLAY_DATE_US: 'MMM DD, YYYY',
  DISPLAY_DATE_US_SHORT: 'MMM D, YYYY',
  DISPLAY_DATE_US_SHORT_YEAR: 'MMM D, YY',
  DISPLAY_DATE_US_FULL: 'MMMM DD, YYYY',
  DISPLAY_DATE_US_FULL_SHORT: 'MMMM D, YYYY',
  DISPLAY_DATE_DAY_MONTH: 'DD MMM',
  DISPLAY_DATE_MONTH_DAY: 'MMM DD',
  DISPLAY_DATE_WITH_WEEKDAY: 'ddd, DD MMM YYYY',
  DISPLAY_DATE_WITH_WEEKDAY_FULL: 'dddd, DD MMM YYYY',
  DISPLAY_DATE_SHORT_YEAR_DASH: 'DD-MMM-YY',
  DISPLAY_MONTH_YEAR: 'MMM YYYY',
  DISPLAY_MONTH_YEAR_FULL: 'MMMM YYYY',
  
  // Alternative date formats
  DATE_UNDERSCORE: 'YYYY_MM_DD',
  DATE_DOT: 'YYYY.MM.DD',
  
  // Time formats
  DISPLAY_TIME_12: 'hh:mm A',
  DISPLAY_TIME_12_NO_LEADING: 'h:mm A',
  DISPLAY_TIME_12_WITH_AT: '@ h:mm A',
  DISPLAY_TIME_24: 'HH:mm',
  DISPLAY_TIME_FULL_12: 'hh:mm:ss A',
  DISPLAY_TIME_FULL_24: 'HH:mm:ss',
  DISPLAY_TIME_HOUR_12: 'hh A',
  DISPLAY_TIME_HOUR_12_SHORT: 'h A',
  DISPLAY_TIME_HOUR_24: 'HH',
  DISPLAY_TIME_24_NO_LEADING: 'H:mm',
  DISPLAY_TIME_SECONDS_12: 'hh:ss A',
  DISPLAY_TIME_MINUTES_SECONDS: 'mm:ss',
  DISPLAY_TIME_WITH_MS: 'HH:mm:ss.SSS',
  
  // Combined date-time formats
  DISPLAY_DATETIME: 'DD MMM YYYY, hh:mm A',
  DISPLAY_DATETIME_FULL: 'DD MMMM YYYY, hh:mm:ss A',
  DISPLAY_DATETIME_SHORT: 'DD/MM/YYYY HH:mm',
  DISPLAY_DATETIME_LONG: 'dddd, DD MMMM YYYY, hh:mm A',
  DISPLAY_DATETIME_ISO_SHORT: 'YYYY-MM-DD HH:mm',
  DISPLAY_DATETIME_ISO_12: 'YYYY-MM-DD h:mm A',
  DISPLAY_DATETIME_ISO_12_PADDED: 'YYYY-MM-DD hh:mm A',
  DISPLAY_DATETIME_ISO_12_WITH_AT: 'YYYY-MM-DD @ h:mm A',
  DISPLAY_DATETIME_ISO_12_SECONDS: 'YYYY-MM-DD h:mm:ss A',
  DISPLAY_DATETIME_ISO_12_SECONDS_PADDED: 'YYYY-MM-DD hh:mm:ss A',
  DISPLAY_DATETIME_ISO_12_SECONDS_WITH_AT: 'YYYY-MM-DD @ h:mm:ss A',
  
  // Hotel specific formats
  CHECK_IN_OUT: 'DD MMM YYYY',
  BOOKING_DATE: 'DD/MM/YYYY',
  INVOICE_DATE: 'DD-MMM-YYYY',
  REPORT_DATE: 'YYYY-MM-DD',
  
  // Indian formats
  INDIAN_DATE: 'DD-MM-YYYY',
  INDIAN_DATE_SHORT: 'DD-MM-YY',
  INDIAN_DATE_SLASH: 'DD/MM/YYYY',
  INDIAN_DATETIME: 'DD/MM/YYYY, HH:mm',
  INDIAN_DATETIME_WITH_SECONDS: 'DD/MM/YYYY, HH:mm:ss',
  INDIAN_DATETIME_AMPM: 'DD-MM-YYYY, h:mm A',
  INDIAN_DATETIME_24: 'DD-MM-YYYY HH:mm',
  INDIAN_DATETIME_SHORT_AMPM: 'DD-MM-YY; hh:mm A',
  
  // Timestamp formats
  TIMESTAMP: 'YYYY-MM-DD HH:mm:ss',
  TIMESTAMP_SHORT: 'YYYY-MM-DD HH:mm',
  TIMESTAMP_WITH_ZONE: 'YYYY-MM-DD HH:mm:ss Z',
  TIMESTAMP_WITH_DOT_SECONDS: 'YYYY-MM-DD HH:mm.ss',
  
  // File naming formats
  FILE_DATE: 'YYYYMMDD',
  FILE_DATETIME: 'YYYYMMDD_HHmmss',
  FILE_DATETIME_MINUTES: 'YYYYMMDDHHmm',
  FILE_DATETIME_MINUTES_UNDERSCORE: 'YYYYMMDD_HHmm',
  FILE_DATETIME_DOT_MINUTES: 'YYYY.MM.DD.HHmm',
  FILE_DATETIME_DASH_MINUTES: 'YYYY-MM-DD-HHmm',
  FILE_DATETIME_UNDERSCORE_MINUTES: 'YYYY-MM-DD_HHmm',
  FILE_DATETIME_DOT_MINUTES_SEPARATED: 'YYYY.MM.DD.HH.mm',
  FILE_DATETIME_DASH_MINUTES_SEPARATED: 'YYYY-MM-DD-HH-mm',
  FILE_DATETIME_DOT_SECONDS: 'YYYY.MM.DD.HHmmss',
  FILE_DATETIME_DASH_SECONDS: 'YYYY-MM-DD-HHmmss',
  FILE_DATETIME_UNDERSCORE_SECONDS: 'YYYY-MM-DD_HHmmss',
  FILE_DATETIME_UNDERSCORE_SECONDS_DOT: 'YYYY-MM-DD_HHmm.ss',
  FILE_DATETIME_DOT_SECONDS_SEPARATED: 'YYYY.MM.DD.HH.mm.ss',
  FILE_DATETIME_DASH_SECONDS_SEPARATED: 'YYYY-MM-DD-HH-mm-ss',
  
  // Database formats
  DB_DATE: 'YYYY-MM-DD',
  DB_DATETIME: 'YYYY-MM-DD HH:mm:ss',
  DB_TIMESTAMP: 'YYYY-MM-DD HH:mm:ss.SSS',
  
  // Weekday date formats
  WEEKDAY_DATE_SHORT_YEAR: 'dd MMM D YY',
  WEEKDAY_DATE_ABBR_SHORT_YEAR: 'ddd MMM D YY',
  WEEKDAY_DATE_ABBR_SHORT: 'ddd MMM D YYYY',
  WEEKDAY_DATE_ABBR: 'ddd MMM DD YYYY',
  WEEKDAY_DATE_FULL_SHORT: 'dddd, MMM D YYYY',
  WEEKDAY_DATE_FULL_MONTH_SHORT: 'dddd, MMMM D, YYYY',
  WEEKDAY_DATE_FULL_MONTH: 'dddd, MMMM DD, YYYY',
  
  // Weekday date-time formats with h:mm A
  WEEKDAY_DATETIME_ABBR_SHORT_YEAR: 'ddd MMM D YY h:mm A',
  WEEKDAY_DATETIME_ABBR_SHORT: 'ddd MMM D YYYY h:mm A',
  WEEKDAY_DATETIME_ABBR: 'ddd MMM DD YYYY h:mm A',
  WEEKDAY_DATETIME_FULL_SHORT: 'dddd, MMM D YYYY h:mm A',
  WEEKDAY_DATETIME_FULL_MONTH_SHORT: 'dddd, MMMM D, YYYY h:mm A',
  WEEKDAY_DATETIME_FULL_MONTH: 'dddd, MMMM DD, YYYY h:mm A',
  
  // Weekday date-time formats with hh:mm A
  WEEKDAY_DATETIME_ABBR_SHORT_YEAR_PADDED: 'ddd MMM D YY hh:mm A',
  WEEKDAY_DATETIME_ABBR_SHORT_PADDED: 'ddd MMM D YYYY hh:mm A',
  WEEKDAY_DATETIME_ABBR_PADDED: 'ddd MMM DD YYYY hh:mm A',
  WEEKDAY_DATETIME_FULL_SHORT_PADDED: 'dddd, MMM D YYYY hh:mm A',
  WEEKDAY_DATETIME_FULL_MONTH_SHORT_PADDED: 'dddd, MMMM D, YYYY hh:mm A',
  WEEKDAY_DATETIME_FULL_MONTH_PADDED: 'dddd, MMMM DD, YYYY hh:mm A',
  
  // Weekday date-time formats with @ h:mm A
  WEEKDAY_DATETIME_ABBR_SHORT_YEAR_AT: 'ddd MMM D YY @ h:mm A',
  WEEKDAY_DATETIME_ABBR_SHORT_AT: 'ddd MMM D YYYY @ h:mm A',
  WEEKDAY_DATETIME_ABBR_AT: 'ddd MMM DD YYYY @ h:mm A',
  WEEKDAY_DATETIME_FULL_SHORT_AT: 'dddd, MMM D YYYY @ h:mm A',
  WEEKDAY_DATETIME_FULL_MONTH_SHORT_AT: 'dddd, MMMM D, YYYY @ h:mm A',
  WEEKDAY_DATETIME_FULL_MONTH_AT: 'dddd, MMMM DD, YYYY @ h:mm A',
} as const;

export const TIME_UNITS = {
  MILLISECOND: 'millisecond',
  SECOND: 'second',
  MINUTE: 'minute',
  HOUR: 'hour',
  DAY: 'day',
  WEEK: 'week',
  MONTH: 'month',
  QUARTER: 'quarter',
  YEAR: 'year',
} as const;

export const DAY_OF_WEEK = {
  SUNDAY: 0,
  MONDAY: 1,
  TUESDAY: 2,
  WEDNESDAY: 3,
  THURSDAY: 4,
  FRIDAY: 5,
  SATURDAY: 6,
} as const;

export const MONTH_OF_YEAR = {
  JANUARY: 0,
  FEBRUARY: 1,
  MARCH: 2,
  APRIL: 3,
  MAY: 4,
  JUNE: 5,
  JULY: 6,
  AUGUST: 7,
  SEPTEMBER: 8,
  OCTOBER: 9,
  NOVEMBER: 10,
  DECEMBER: 11,
} as const;

export const HOTEL_TIMINGS = {
  CHECK_IN_TIME: '14:00',  // 2:00 PM
  CHECK_OUT_TIME: '11:00', // 11:00 AM
  NIGHT_AUDIT_TIME: '00:00', // Midnight
  LATE_CHECK_OUT_TIME: '18:00', // 6:00 PM
} as const;

export const DATE_RANGES = {
  TODAY: 'today',
  YESTERDAY: 'yesterday',
  THIS_WEEK: 'this_week',
  LAST_WEEK: 'last_week',
  THIS_MONTH: 'this_month',
  LAST_MONTH: 'last_month',
  THIS_QUARTER: 'this_quarter',
  LAST_QUARTER: 'last_quarter',
  THIS_YEAR: 'this_year',
  LAST_YEAR: 'last_year',
  LAST_7_DAYS: 'last_7_days',
  LAST_30_DAYS: 'last_30_days',
  LAST_90_DAYS: 'last_90_days',
  CUSTOM: 'custom',
} as const;

export const MILLISECONDS_IN = {
  SECOND: 1000,
  MINUTE: 60 * 1000,
  HOUR: 60 * 60 * 1000,
  DAY: 24 * 60 * 60 * 1000,
  WEEK: 7 * 24 * 60 * 60 * 1000,
} as const;

export const SECONDS_IN = {
  MINUTE: 60,
  HOUR: 3600,
  DAY: 86400,
  WEEK: 604800,
  MONTH: 2592000, // Approximate (30 days)
  YEAR: 31536000, // Approximate (365 days)
} as const;

export const MINUTES_IN = {
  HOUR: 60,
  DAY: 1440,
  WEEK: 10080,
} as const;

export const HOURS_IN = {
  DAY: 24,
  WEEK: 168,
} as const;

export const INDIAN_HOLIDAYS = {
  REPUBLIC_DAY: '01-26',
  INDEPENDENCE_DAY: '08-15',
  GANDHI_JAYANTI: '10-02',
  // Add more holidays as needed
} as const;

export const BUSINESS_DAYS = [
  DAY_OF_WEEK.MONDAY,
  DAY_OF_WEEK.TUESDAY,
  DAY_OF_WEEK.WEDNESDAY,
  DAY_OF_WEEK.THURSDAY,
  DAY_OF_WEEK.FRIDAY,
] as const;

export const WEEKEND_DAYS = [
  DAY_OF_WEEK.SATURDAY,
  DAY_OF_WEEK.SUNDAY,
] as const;
